# Generated by Django 3.2.24 on 2024-03-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='image',
        ),
    ]
